### ISSUE TITLE
Bug: Two icons shows in evaluation scheme

### ISSUE THREAD

**Issue by ghost** [kshitiz-patel/Academic-Resources-Portal#2]
- [x] Bug
![image](https://user-images.githubusercontent.com/79007697/166100694-5dda53bd-5267-44b5-aa34-4943d74ef7be.png)

Problem :
Two icons are included in code 
one is by bootstrap icon
and another one is by svg

Solution : 
delete the icon which was implemented by svg

**Comment by kshitiz-patel** [comment]
Issue Resolved
